services:
  postgres:
    image: postgres:16-alpine
    container_name: skild-postgres
    environment:
      POSTGRES_DB: skild
      POSTGRES_USER: skild
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # # keycloak:
  #   image: quay.io/keycloak/keycloak:26.1
  #   container_name: skild-keycloak
  #   command: start-dev --import-realm
  #   environment:
  #     KC_DB: postgres
  #     KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  #     KC_DB_USERNAME: keycloak
  #     KC_DB_PASSWORD: keycloak_password
  #     KC_BOOTSTRAP_ADMIN_USERNAME: admin
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  #     KC_HTTP_PORT: 8180
  #     KC_HOSTNAME_STRICT: false
  #   volumes:
  #     - ./docker/keycloak:/opt/keycloak/data/import
  #   ports:
  #     - "8180:8180"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
