/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiAdminSyncSkillsRouteImport } from './routes/api/admin/sync-skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSyncSkillsRoute = ApiAdminSyncSkillsRouteImport.update({
  id: '/api/admin/sync-skills',
  path: '/api/admin/sync-skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
  '/api/admin/sync-skills': typeof ApiAdminSyncSkillsRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills': typeof SkillsIndexRoute
  '/api/admin/sync-skills': typeof ApiAdminSyncSkillsRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
  '/api/admin/sync-skills': typeof ApiAdminSyncSkillsRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills/$skillId'
    | '/skills/'
    | '/api/admin/sync-skills'
    | '/api/webhooks/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/skills/$skillId'
    | '/skills'
    | '/api/admin/sync-skills'
    | '/api/webhooks/github'
  id:
    | '__root__'
    | '/'
    | '/skills/$skillId'
    | '/skills/'
    | '/api/admin/sync-skills'
    | '/api/webhooks/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ApiAdminSyncSkillsRoute: typeof ApiAdminSyncSkillsRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sync-skills': {
      id: '/api/admin/sync-skills'
      path: '/api/admin/sync-skills'
      fullPath: '/api/admin/sync-skills'
      preLoaderRoute: typeof ApiAdminSyncSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ApiAdminSyncSkillsRoute: ApiAdminSyncSkillsRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
